name: karibu_kazi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  flutter_osm_plugin: ^0.70.4
  geolocator: ^11.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  # google_maps_flutter: ^2.5.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/img/

